#!/bin/bash 
#PBS -S /bin/bash
#PBS -l nodes=3:ppn=12 
#PBS -l mem=66gb 
#PBS -l walltime=1:00:00 
#PBS -m bea
#PBS -M aaron.stanton@ualberta.ca
#PBS -N 01_adj
#PBS -o 01_adj.out
#PBS -e 01_adj.err

date

# Change to directory from which job was submitted
cd $PBS_O_WORKDIR 

echo "here is your PBS_NODEFILE"
cat $PBS_NODEFILE | uniq > machines.txt
cat machines.txt

export OMP_NUM_THREADS=12

echo "calling julia now"
julia --machinefile machines.txt tmp.jl

